apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-manual-testing-llamacpp-1-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/chatbot-manual-testing-llamacpp-1/overlays/development
    repoURL: https://github.com/fpetk/chatbot-manual-testing-llamacpp-1-gitops.git
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: ai-rhdh
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
